---
title: "Foundations of Python"
author: Hamish Gibbs
---

## Welcome

Welcome to the [UCL Social Data Institute](https://www.ucl.ac.uk/social-data/home/social-data-institute) summer course: *Foundations of Python*. 

## Course aims

This course aims to provide:  

* A foundation in Python programming.  
* An Introduction to popular Python tools for data science.  
* A hands-on collaborative data science challenge.

## Requirements

This course is open to students of any programming level, but will assume that students have some experience with R. 

**Important:** Before the course, please install the [required software](./required_software.qmd).

## Structure

This course will take place over 4 days and will be structured into morning (10:00 – 13:00) and afternoon (14:00 – 16:00) periods. 

I will remain in the classroom after 16:00 each day to provide assistance / answer any questions.

Days 1 – 3 will focus on introducing the basics of Python, building up to the use of popular data science libraries (pandas, numpy, matplotlib, and sklearn). We will also discuss running Python code in an Integrated Development Environment (VSCode), and will introduce collaboration tools (git and GitHub).

Day 4 will be based around a collaborative data science challenge. You can work individually or in small groups. In the afternoon, we will have a friendly discussion of everyone's solutions!

## Contact

If you have any questions before the start of the course, please email me at [Hamish.Gibbs.21@ucl.ac.uk](mailto:Hamish.Gibbs.21@ucl.ac.uk)!
