---
title: "Course schedule"
author: Hamish Gibbs
---

## Where and when

**Dates:** 20th to 23rd May, 2024. 

**Time:** 10:00 – 16:00 every day.

**Location:** [1-19 Torrington Place](https://maps.app.goo.gl/u9iX38uM1TyYpn3E9), Room B07.

## Schedule

### Day 1 (Python basics)

| Time | Session Type | Content |
|-|-|--|
| 10:00 – 11:00 | Lecture / Live Coding | [[PDF]](./slides/slides_introduction.pdf) [[HTML]](./slides/slides_introduction.qmd) |
| 11:00 – 12:30 | Practical | 1. [Variables, expressions, and statements](https://www.py4e.com/html3/02-variables) <br> 2. [An informal introduction to python §3.1.3](https://docs.python.org/3/tutorial/introduction.html#lists) <br> 3. [Dictionaries §1](https://www.py4e.com/html3/09-dictionaries) |
| 12:30 – 13:30 | Lunch | 
| 13:30 – 14:30 | Lecture / Live Coding | [[PDF]](./slides/slides_control_logic.pdf) [[HTML]](./slides/slides_control_logic.qmd) |
| 14:30 – 16:00 | Practical | 1. [Conditional execution](https://www.py4e.com/html3/03-conditional) <br> 2. [Iteration](https://www.py4e.com/html3/05-iterations) <br> 3. [More control flow tools §4.1-4.6](https://docs.python.org/3/tutorial/controlflow.html)

### Day 2 (Abstraction & composition)

| Time | Session Type | Content |
|-|-|--|
| 10:00 – 11:00 | Lecture / Live Coding | [[PDF]](./slides/slides_abstraction_and_composition.pdf) [[HTML]](./slides/slides_abstraction_and_composition.qmd) |
| 11:00 – 12:30 | Practical | 1. [Functions](https://www.py4e.com/html3/04-functions) <br> 2. [Object-oriented programming](https://www.py4e.com/html3/14-objects) <br> 3. [More control flow tools §4.7-4.8 (Optional)](https://docs.python.org/3/tutorial/controlflow.html#defining-functions)|
| 12:30 – 13:30 | Lunch | 
| 13:30 – 14:30 | Lecture / Live Coding | [[PDF]](./slides/slides_vscode_python.pdf) [[HTML]](./slides/slides_vscode_python.qmd) |
| 14:30 – 16:00 | Practical | 1. [Python Interactive window](https://code.visualstudio.com/docs/python/jupyter-support-py) <br> 2. *Continue practicals above* <br> 3. [Solution](https://colab.research.google.com/drive/1yVVDZlKoaZhARko4AO6qqqtlexOVoTSD?usp=sharing) for the "Extra" exercise. |

### Day 3 (Python data science)

| Time | Session Type | Content |
|-|-|--|
| 10:00 – 11:00 | Lecture / Live Coding | [[PDF]](./slides/slides_python_data_science.pdf) [[HTML]](./slides/slides_python_data_science.qmd) |
| 11:00 – 12:30 | Practical | 1. [pandas-cookbook: Selecting data (Chapter 2)](https://nbviewer.org/github/jvns/pandas-cookbook/blob/master/cookbook/Chapter%202%20-%20Selecting%20data%20&%20finding%20the%20most%20common%20complaint%20type.ipynb) <br> 2. [pandas-cookbook: More selecting data (Chapter 3)](https://nbviewer.org/github/jvns/pandas-cookbook/blob/master/cookbook/Chapter%203%20-%20Which%20borough%20has%20the%20most%20noise%20complaints%20%28or%2C%20more%20selecting%20data%29.ipynb) <br> 3. [sklearn - Getting Started](https://scikit-learn.org/stable/getting_started.html) <br> Reference: [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) <br> Reference: [pandas: Chart visualization](https://pandas.pydata.org/docs/user_guide/visualization.html) <br> Reference: [scikitlearn: Examples](https://scikit-learn.org/stable/auto_examples/index.html#general-examples) |
| 12:30 – 13:30 | Lunch | 
| 13:30 – 14:30 | Lecture / Live Coding | [[PDF]](./slides/slides_collaboration.pdf) [[HTML]](./slides/slides_collaboration.qmd) |
| 14:30 – 16:00 | Practical | 1. Setup a [GitHub](https://github.com/) account <br> 2. [Create a GitHub repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository) <br> 3. Commit your code ([Add](https://github.com/git-guides/git-add), [Commit](https://github.com/git-guides/git-commit)). <br> 4. Push your code to your repository ([Remote](https://github.com/git-guides/git-remote), [Push](https://github.com/git-guides/git-push)) |

### Day 4 (Challenge: regression analysis)

| Time | Session Type | Content |
|-|-|--|
| 10:00 – 11:00 | Lecture / Live Coding | [[PDF]](./slides/slides_regression.pdf) [[HTML]](./slides/slides_regression.qmd) |
| 11:00 – 12:30 | Challenge | 1. Start the [Challenge](./challenge.qmd)! <br> For help see: [sklearn](https://scikit-learn.org/stable/tutorial/index.html) tutorials and [Inside AirBnB](https://insideairbnb.com/). |
| 12:30 – 13:30 | Lunch | 
| 13:30 – 16:00 | Challenge | 1. Push your solution file to the [shared repository](https://github.com/hamishgibbs/sdi_python_foundations_2024). <br> 2. We will discuss / compare solutions! |