---
title: "Python data science (continued)"
author: Hamish Gibbs
format: revealjs
---

## Tutorial #3: String operations

* [pandas-cookbook: String operations (Chapter 6)](https://nbviewer.org/github/jvns/pandas-cookbook/blob/master/cookbook/Chapter%206%20-%20String%20Operations-%20Which%20month%20was%20the%20snowiest.ipynb)
    * This tutorial is about extracting information from text in `pandas`.
    * *Hint: Some of the most interesting information in tomorrow's dataset might be in string variables.*
* Core concepts: 
    * Detecting keywords in strings:

        ```python
        weather_description.str.contains('Snow')
        ```

## Tutorial #4: Data cleaning

* [pandas-cookbook: Data cleaning (Chapter 7)](https://nbviewer.org/github/jvns/pandas-cookbook/blob/master/cookbook/Chapter%207%20-%20Cleaning%20up%20messy%20data.ipynb)
* Core concepts: 
    * Detecting `nan` values stored as strings:

        ```python
        na_values = ['NO CLUE', 'N/A', '0']
        requests = pd.read_csv(..., na_values=na_values, ...)
        ```
    * Altering `DataFrame` values in-place:
        
        ```python
        zero_zips = requests['Incident Zip'] == '00000'
        requests.loc[zero_zips, 'Incident Zip'] = np.nan
        ```

## Tutorial #5: sklearn - Linear Regression

* [sklearn - Linear Regression Example](https://scikit-learn.org/stable/auto_examples/linear_model/plot_ols.html)
* Core concepts: 
    * Fitting a model to data
    
        ```python
        regr.fit(diabetes_X_train, diabetes_y_train)
        ```
    * Making predictions with a model

        ```python
        regr.predict(diabetes_X_test)
        ```
    
    * Model evaluation
    
        ```python
        mean_squared_error(diabetes_y_test, diabetes_y_pred)
        ```

## Challenge scaffold

* [challenge_scaffold.py](https://github.com/hamishgibbs/soda_python_foundations/blob/main/challenge_scaffold.py)
    * Look at the [Challenge Guidelines](../challenge.qmd) and the project scaffold.
    * I will walk through the challenge scaffold!
    * Use this scaffold as a starting point for the challenge tomorrow.

## Extra

* Start working with the [dataset](https://github.com/hamishgibbs/sdi_python_foundations/blob/main/data) we will use tomorrow. 
* Work on a few of the items in the challenge: 
    * *What variables are in the dataset?*
    * *What are the data types of the variables?*
    * *Is there any missing data?*

